const CharList = {
    'ssr': [
        { path: "images/5star/Venti.png", name: "温迪", type: "角色", rarity: "5★" },
        { path: "images/5star/char_zhongli.png", name: "钟离", type: "角色", rarity: "5★" },
        { path: "images/5star/char_raiden.png", name: "雷电将军", type: "角色", rarity: "5★" },
        { path: "images/5star/char_nahida.png", name: "纳西妲", type: "角色", rarity: "5★" },
        { path: "images/5star/Klee.png", name: "可莉", type: "角色", rarity: "5★" },
        { path: "images/5star/Jean.png", name: "琴", type: "角色", rarity: "5★" },
        { path: "images/5star/Diluc.png", name: "迪卢克", type: "角色", rarity: "5★" },
        { path: "images/5star/Eula.png", name: "优菈", type: "角色", rarity: "5★" },
        { path: "images/5star/Mona.png", name: "莫娜", type: "角色", rarity: "5★" },
        { path: "images/5star/Tartaglia.png", name: "达达利亚", type: "角色", rarity: "5★" },
        { path: "images/5star/Arataki_Itto.png",name:"荒泷一斗",type:"角色",rarity:"5★"},
        { path: "images/5star/Xiao.png", name: "魈", type: "角色", rarity: "5★" },
        { path: "images/5star/Shenhe.png", name: "申鹤", type: "角色", rarity: "5★" },
        { path: "images/5star/Hu_Tao.png", name: "胡桃", type: "角色", rarity: "5★" },
        { path: "images/5star/Keqing.png", name: "刻晴", type: "角色", rarity: "5★" },
        { path: "images/5star/Ganyu.png", name: "甘雨", type: "角色", rarity: "5★" },
        { path: "images/5star/Tighnari.png", name: "提纳里", type: "角色", rarity: "5★" },
        { path: "images/5star/Cyno.png", name: "赛诺", type: "角色", rarity: "5★" },
        { path: "images/5star/Yae_Miko.png", name: "八重神子", type: "角色", rarity: "5★" },
        { path: "images/5star/Kamizato_Ayaka.png", name: "神里绫华", type: "角色", rarity: "5★" },
        { path: "images/5star/Kamizato_Ayato.png", name: "神里绫人", type: "角色", rarity: "5★" },
        { path: "images/5star/Yoimiya.png", name: "宵宫", type: "角色", rarity: "5★" },
        { path: "images/5star/Sangonomiya_Kokomi.png", name: "珊瑚宫心海", type: "角色", rarity: "5★" },
        { path:"images/5star/Escofier.png",name:"爱可菲",type:"角色",rarity: "5★"},
        { path:"images/5star/Skirk.png",name:"丝柯克",type:"角色",rarity: "5★"},
        { path: "images/5star/Maguu_Kenki.png", name: "魔偶剑鬼", type: "魔物", rarity: "5★" },
        { path: "images/5star/Rhodeia_of_Loch.png", name: "纯水精灵·洛蒂娅", type: "魔物", rarity: "5★" },
        { path: "images/5star/Gold_Lawachurls.png", name: "黄金丘丘王", type: "魔物", rarity: "5★" },
        { path: "images/5star/Jadeplume_Terrorshroom.png", name: "翠翎恐蕈", type: "魔物", rarity: "5★" },
        { path: "images/5star/Agents.png", name: "愚人众·债务处理人", type: "魔物", rarity: "5★" },
        { path: "images/5star/Mirror_Maiden.png", name: "愚人众·藏镜仕女", type: "魔物", rarity: "5★" },
        { path: "images/5star/Hydro_Tulpa.png",name: "水形幻人",type: "魔物",rarity: "5★"},
        { path: "images/5star/Gluttonous_Yumkasaur_Mountain_King.png",name: "贪食匿叶龙山王",type: "魔物",rarity: "5★"},
        { path: "images/5star/Black_Serpent_Knight_Rockbreaker_Ax.png",name: "黑蛇骑士·摧岩之钺",type: "魔物",rarity: "5★"},
        { path: "images/5star/Amos_bow.png", name: "阿莫斯之弓", type: "武器", rarity: "5★" },
        { path: "images/5star/A_Thousand_Floating_Dreams.png", name: "千夜浮梦", type: "武器", rarity: "5★" },
        { path: "images/5star/Engulfing_Lightning.png", name: "薙草之稻光", type: "武器", rarity: "5★" },
        { path: "images/5star/Skyward_Atlas.png", name: "天空之卷", type: "武器", rarity: "5★" },
        { path: "images/5star/Skyward_Harp.png", name: "天空之翼", type: "武器", rarity: "5★" },
        { path: "images/5star/Skyward_Spine.png", name: "天空之脊", type: "武器", rarity: "5★" },
        { path: "images/5star/Wolf_Gravestone.png", name: "狼的末路", type: "武器", rarity: "5★" }
    ],
    'sr': [
        { path: "images/4star/Kaeya.png", name: "凯亚", type: "角色", rarity: "4★" },
        { path: "images/4star/Amber.png", name: "安柏", type: "角色", rarity: "4★" },
        { path: "images/4star/Barbara.png", name: "芭芭拉", type: "角色", rarity: "4★" },
        { path: "images/4star/Noelle.png", name: "诺艾尔", type: "角色", rarity: "4★" },
        { path: "images/4star/Diona.png", name: "迪奥娜", type: "角色", rarity: "4★" },
        { path: "images/4star/Fischl.png", name: "菲谢尔", type: "角色", rarity: "4★" },
        { path: "images/4star/Sucrose.png", name: "砂糖", type: "角色", rarity: "4★" },
        { path: "images/4star/Razor.png", name: "雷泽", type: "角色", rarity: "4★" },
        { path: "images/4star/char_bennett.png", name: "班尼特", type: "角色", rarity: "4★" },
        { path: "images/4star/Ningguang.png", name: "凝光", type: "角色", rarity: "4★" },
        { path: "images/4star/Beidou.png", name: "北斗", type: "角色", rarity: "4★" },
        { path: "images/4star/char_xingqiu.png", name: "行秋", type: "角色", rarity: "4★" },
        { path: "images/4star/Chongyun.png", name: "重云", type: "角色", rarity: "4★" },
        { path: "images/4star/char_xiangling.png", name: "香菱", type: "角色", rarity: "4★" },
        { path: "images/4star/Collei.png", name: "柯莱", type: "角色", rarity: "4★" },
        { path: "images/4star/Kujo_Sara.png", name: "九条裟罗", type: "角色", rarity: "4★" },
        { path: "images/4star/Anemo_Samachurl.png",name: "丘丘风萨满",type: "魔物",rarity: "4★"},
        { path: "images/4star/Electro_Samachurl.png",name: "丘丘雷萨满",type: "魔物",rarity: "4★"},
        { path: "images/4star/Hydro_Samachurl.png",name: "丘丘水萨满",type: "魔物",rarity: "4★"},
        { path: "images/4star/Dendro_Samachurl.png",name: "丘丘草萨满",type: "魔物",rarity: "4★"},
        { path: "images/4star/Geo_Samachurl.png",name: "丘丘岩萨满",type: "魔物",rarity: "4★"},
        { path: "images/4star/Pyro_Abyss_Mage.png",name: "火深渊法师",type: "魔物",rarity: "4★"},
        { path: "images/4star/Electro_Abyss_Mage.png",name: "雷深渊法师",type: "魔物",rarity: "4★"},
        { path: "images/4star/Hydro_Abyss_Mage.png",name: "水深渊法师",type: "魔物",rarity: "4★"},
        { path: "images/4star/Cryo_Abyss_Mage.png",name: "冰深渊法师",type: "魔物",rarity: "4★"},
        { path: "images/4star/Blazing_Axe_Mitachurl.png",name: "火斧丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/4star/Crackling_Axe_Mitachurl.png",name: "雷斧丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/4star/Wooden_Shieldwall_Mitachurl.png",name: "木盾丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/4star/Rock_Shieldwall_Mitachurl.png",name: "岩盾丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/4star/Ice_Shieldwall_Mitachurl.png",name: "冰盾丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/4star/Kairagi_Dancing_Thunder.png",name: "海乱鬼·雷腾",type: "魔物",rarity: "4★"},
        { path: "images/4star/Kairagi_Fiery_Might.png",name: "海乱鬼·炎威",type: "魔物",rarity: "4★"},
        { path: "images/4star/Grounded_Hydroshroom.png",name: "陆行水本真蕈",type: "魔物",rarity: "4★"},
        { path: "images/4star/Grounded_Geoshroom.png",name: "陆行岩本真蕈",type: "魔物",rarity: "4★"},
        { path: "images/4star/Winged_Dendroshroom.png",name: "有翼草本真蕈",type: "魔物",rarity: "4★"},
        { path: "images/4star/Winged_Cryoshroom.png",name: "有翼冰本真蕈",type: "魔物",rarity: "4★"},
        { path: "images/4star/Thundercraven_Rifthound_Whelp.png",name: "嗜雷·兽境猎犬",type: "魔物",rarity: "4★"},
        { path: "images/4star/Rockfond_Rifthound_Whelp.png",name: "嗜岩·兽境猎犬",type: "魔物",rarity: "4★"},
        { path: "images/4star/Suppression_Specialist_Mek.png",name: "攻坚特化型机关",type: "魔物",rarity: "4★"},
        { path: "images/4star/Annihilation_Specialist_Mek.png",name: "歼灭特化型机关",type: "魔物",rarity: "4★"},
        { path: "images/4star/Fatui_Skirmisher-Anemoboxer_Vanguard.png",name: "愚人众先遣队·风拳前锋军",type: "魔物",rarity: "4★"},
        { path: "images/4star/Fatui_Skirmisher-Cryogunner_Legionnaire.png",name: "愚人众先遣队·冰铳重卫士",type: "魔物",rarity: "4★"},
        { path: "images/4star/Fatui_Skirmisher-Hydrogunner_Legionnaire.png",name: "愚人众先遣队·水铳重卫士",type: "魔物",rarity: "4★"},
        { path: "images/4star/Consecrated_Horned_Crocodile.png",name: "圣骸角鳄",type: "魔物",rarity: "4★"},
        { path: "images/4star/Sacrificial_Sword.png", name: "祭礼剑", type: "武器", rarity: "4★" },
        { path: "images/4star/Sacrificial_Fragments.png", name: "祭礼残章", type: "武器", rarity: "4★" },
        { path: "images/4star/Sacrificial_Greatsword.png", name: "祭礼大剑", type: "武器", rarity: "4★" },
        { path: "images/4star/Sacrificial_Bow.png", name: "祭礼弓", type: "武器", rarity: "4★" },
        { path: "images/4star/Lithic_Spear.png", name: "千岩长枪", type: "武器", rarity: "4★" },
        { path: "images/4star/Large_Cryo_Slime.png", name: "大型冰史莱姆", type: "魔物", rarity: "4★" },
        { path: "images/4star/Large_Hydro_Slime.png", name: "大型水史莱姆", type: "魔物", rarity: "4★" }
    ],
    'r': [
        { path: "images/3star/Hydro_Slime.png", name: "水史莱姆", type: "魔物", rarity: "3★" },
        { path: "images/3star/Cryo_Slime.png", name: "冰史莱姆", type: "魔物", rarity: "3★" },
        { path: "images/3star/Electro_Slime.png", name: "雷史莱姆", type: "魔物", rarity: "3★" },
        { path: "images/3star/Arithmetic_Enhancer_Mek.png",name: "机关·算力振幅器",type: "魔物",rarity: "3★"},
        { path: "images/3star/Pyro_Whopperflower.png",name: "炽热骗骗花",type: "魔物",rarity: "3★"},
        { path: "images/3star/Hilichurl_Fighter.png",name: "打手丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/3star/Hilichurl_Berserker.png",name: "冲锋丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/3star/Hilichurl_Shooter.png",name: "射手丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/3star/Electro_Hilichurl_Shooter.png",name: "雷弹丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/3star/Cryo_Hilichurl_Shooter.png",name: "冰箭丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/3star/Nobushi_Jintouban.png",name: "野伏·阵刀番",type: "魔物",rarity: "3★"},
        { path: "images/3star/Nobushi_Hitsukeban.png",name: "野伏·火付番",type: "魔物",rarity: "3★"},
        { path: "images/3star/Nobushi_Kikouban.png",name: "野伏·机巧番",type: "魔物",rarity: "3★"},
        { path: "images/3star/weapon_bow.png", name: "鸦羽弓", type: "武器", rarity: "3★" },
        { path: "images/3star/weapon_claymore.png", name: "白铁大剑", type: "武器", rarity: "3★" },
        { path: "images/3star/weapon_book.png", name: "魔导绪论", type: "武器", rarity: "3★" },
        { path: "images/3star/Traverler_Sword.png", name: "旅行剑", type: "武器", rarity: "3★" },
        { path: "images/3star/White_Tassel.png", name: "白缨枪", type: "武器", rarity: "3★" }
    ]
};


